#!/usr/bin/groovy
// by Nag


pipeline {
    agent any
    environment {
        DOCKER_IMAGE_NAME = "mayank2610/movieApp"
    }
    stages {
        stage('Build') {
             steps {
              dir('case-studies/_SSR') {
                sh 'npm install'
                sh 'npm test'
              }
            }
        }
        stage('Build Docker Image') {
            steps {
              dir('case-studies/_SSR') {
                script {
                    app = docker.build(DOCKER_IMAGE_NAME)
                }
              }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'team2-docker-hub-credentials') {
                        app.push("${env.BUILD_NUMBER}")
                        //app.push("latest")
                    }
                }
            }
        }
        stage('DeployToProduction') {
            steps {
                input 'Deploy to Production?'
                milestone(1)
                //implement Kubernetes deployment here
            }
        }
    }
}